### PR TITLE
Html5

### PR DESCRIPTION
**Pull request by anteprandium**
Handle starred version of DeclareMathOperator and use \operatorname instead of \mathrm

There’s a full discussion of \operatorname vs \mathrm in
http://tex.stackexchange.com/questions/48459/whats-the-difference-betwee
n-mathrm-and-operatorname#answer-48463
In essence, \mathrm is not correct.

Note that MathJax appropriately handles \operatorname.

### CODE REVIEW

**Comment by anteprandium** [comment]
Damn! I screwed up with git, very much sorry about that. I wanted to PR to @PatrickMassot html5 branch. How do I go back?

**Comment by pkra** [comment]
If you edit the title of the PR, you can switch branches, too.

**Comment by anteprandium** [comment]
@pkra The thing is, I wanted to PR to @PatrickMassot html5 branch, not the master branch from here. Can I cancel this PR as if it never happened?

**Comment by pkra** [comment]
Ah, sorry. I think you can only close this one and open a new one to the other fork.

**Comment by anteprandium** [comment]
Thanks again. I apologise to all involved in this.

**Comment by PatrickMassot** [comment]
@anteprandium I can't see any PR on my side. And I also can't see your code here. What did you want to modify?

**Comment by anteprandium** [comment]
Sorry for the delayed answer, I was off the grid for a few days. And yes, I am a bit PR-shy right now, after this horrible mistake. :)  

Anyway,  originally, you had \mathrm instead of \operatorname in `amsmath.py`,  but it's been corrected as of #54. Thanks very much.

**Comment by PatrickMassot** [comment]
Ok, I'm happy I understood you correctly despite github pitfalls. Yesterday I made a series of preparatory pull requests. plasTeX is almost ready for my html5 branch. But I need to write quite a bit of documentation...

**Pull request closed without merging**
